name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Yeh daily raat ko automatically chalega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: joshcai/leetcode-sync@v1.7
      with:
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
        destination-folder: Leetcode-Solutions # Is folder me saare answers aayenge
